port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
proxies:
- name: RU1
  type: socks5
  server: 37.18.73.60
  port: 5566
- name: 美国1
  type: socks5
  server: 47.251.87.199
  port: 9098
- name: 美国2
  type: socks5
  server: 47.254.36.213
  port: 32764
- name: 美国3
  type: socks5
  server: 47.251.73.54
  port: 5060
- name: 美国4
  type: socks5
  server: 47.254.36.213
  port: 20000
- name: 美国5
  type: socks5
  server: 47.251.87.199
  port: 1080
- name: 美国6
  type: socks5
  server: 47.251.73.54
  port: 80
- name: 美国7
  type: socks5
  server: 47.251.73.54
  port: 1081
- name: 美国8
  type: socks5
  server: 47.251.87.199
  port: 1081
- name: 美国9
  type: socks5
  server: 47.254.36.213
  port: 8080
- name: 美国10
  type: socks5
  server: 47.251.74.38
  port: 79
- name: 中国大陆1
  type: socks5
  server: 47.116.210.163
  port: 8054
- name: 中国大陆2
  type: socks5
  server: 47.116.210.163
  port: 3128
- name: 中国大陆3
  type: socks5
  server: 47.116.126.57
  port: 9080
- name: 中国大陆4
  type: socks5
  server: 47.116.126.57
  port: 3128
- name: 中国大陆5
  type: socks5
  server: 47.116.126.57
  port: 80
- name: 中国大陆6
  type: socks5
  server: 47.99.112.148
  port: 9098
- name: 中国大陆7
  type: socks5
  server: 47.99.112.148
  port: 4006
- name: 中国大陆8
  type: socks5
  server: 120.26.52.35
  port: 8080
- name: 中国大陆9
  type: socks5
  server: 120.26.52.35
  port: 3128
- name: 中国大陆10
  type: socks5
  server: 106.14.104.220
  port: 3333
- name: 韩国1
  type: socks5
  server: 8.213.128.6
  port: 9091
- name: 韩国2
  type: socks5
  server: 8.213.134.213
  port: 10000
- name: 韩国3
  type: socks5
  server: 8.213.134.213
  port: 9098
- name: 韩国4
  type: socks5
  server: 8.213.129.20
  port: 55443
- name: 韩国5
  type: socks5
  server: 8.213.134.213
  port: 8080
- name: 韩国6
  type: socks5
  server: 8.213.128.6
  port: 800
- name: 韩国7
  type: socks5
  server: 8.213.128.6
  port: 8085
- name: 韩国8
  type: socks5
  server: 8.220.204.92
  port: 8081
- name: 韩国9
  type: socks5
  server: 8.213.156.191
  port: 3129
- name: 韩国10
  type: socks5
  server: 8.213.129.20
  port: 6789
- name: 德国1
  type: socks5
  server: 8.211.51.115
  port: 8080
- name: 德国2
  type: socks5
  server: 8.209.96.245
  port: 4153
- name: 德国3
  type: socks5
  server: 8.209.96.245
  port: 193
- name: 德国4
  type: socks5
  server: 8.211.51.115
  port: 144
- name: 德国5
  type: socks5
  server: 8.211.42.167
  port: 1081
- name: 德国6
  type: socks5
  server: 8.211.49.86
  port: 50070
- name: 德国7
  type: socks5
  server: 8.211.49.86
  port: 8443
- name: 德国8
  type: socks5
  server: 8.211.42.167
  port: 3129
- name: 德国9
  type: socks5
  server: 8.211.49.86
  port: 7777
- name: 德国10
  type: socks5
  server: 8.211.42.167
  port: 9080
- name: PH1
  type: socks5
  server: 8.220.136.174
  port: 69
- name: PH2
  type: socks5
  server: 8.220.136.174
  port: 12000
- name: PH3
  type: socks5
  server: 8.212.168.170
  port: 8082
- name: PH4
  type: socks5
  server: 8.212.165.164
  port: 5080
- name: PH5
  type: socks5
  server: 8.220.141.8
  port: 3128
- name: PH6
  type: socks5
  server: 8.212.168.170
  port: 3129
- name: PH7
  type: socks5
  server: 8.212.151.166
  port: 3128
- name: PH8
  type: socks5
  server: 8.220.141.8
  port: 50
- name: PH9
  type: socks5
  server: 8.212.151.166
  port: 5060
- name: PH10
  type: socks5
  server: 8.220.136.174
  port: 2000
- name: 香港1
  type: socks5
  server: 47.76.144.139
  port: 80
- name: 香港2
  type: socks5
  server: 47.238.60.156
  port: 88
- name: 香港3
  type: socks5
  server: 47.238.60.156
  port: 6379
- name: 香港4
  type: socks5
  server: 8.210.17.35
  port: 8082
- name: 香港5
  type: socks5
  server: 8.210.17.35
  port: 3128
- name: 香港6
  type: socks5
  server: 8.210.17.35
  port: 14
- name: 香港7
  type: socks5
  server: 47.238.134.126
  port: 14
- name: 香港8
  type: socks5
  server: 47.238.134.126
  port: 1080
- name: 香港9
  type: socks5
  server: 47.238.130.212
  port: 8004
- name: 香港10
  type: socks5
  server: 47.238.60.156
  port: 4002
- name: 日本1
  type: socks5
  server: 8.221.141.88
  port: 8101
- name: 日本2
  type: socks5
  server: 47.74.46.81
  port: 80
- name: 日本3
  type: socks5
  server: 47.74.46.81
  port: 6379
- name: 日本4
  type: socks5
  server: 47.91.29.151
  port: 1311
- name: 日本5
  type: socks5
  server: 8.221.141.88
  port: 9036
- name: 日本6
  type: socks5
  server: 47.91.29.151
  port: 7890
- name: 日本7
  type: socks5
  server: 8.221.141.88
  port: 2379
- name: 日本8
  type: socks5
  server: 47.74.46.81
  port: 10000
- name: 日本9
  type: socks5
  server: 8.221.139.222
  port: 111
- name: 日本10
  type: socks5
  server: 8.221.139.222
  port: 8081
- name: 新加坡1
  type: socks5
  server: 8.219.229.53
  port: 8081
- name: 新加坡2
  type: socks5
  server: 47.237.2.245
  port: 80
- name: 新加坡3
  type: socks5
  server: 47.237.107.41
  port: 6379
- name: 新加坡4
  type: socks5
  server: 8.219.229.53
  port: 4145
- name: 新加坡5
  type: socks5
  server: 47.237.107.41
  port: 8443
- name: 新加坡6
  type: socks5
  server: 47.237.92.86
  port: 6379
- name: 新加坡7
  type: socks5
  server: 8.219.229.53
  port: 13
- name: 新加坡8
  type: socks5
  server: 47.237.2.245
  port: 1081
- name: 新加坡9
  type: socks5
  server: 47.237.107.41
  port: 82
- name: 新加坡10
  type: socks5
  server: 47.237.2.245
  port: 10
- name: ID1
  type: socks5
  server: 8.215.3.250
  port: 8443
- name: ID2
  type: socks5
  server: 8.215.15.163
  port: 8008
- name: ID3
  type: socks5
  server: 149.129.226.9
  port: 1081
- name: ID4
  type: socks5
  server: 8.215.3.250
  port: 9797
- name: ID5
  type: socks5
  server: 149.129.255.179
  port: 8081
- name: ID6
  type: socks5
  server: 149.129.226.9
  port: 5060
- name: ID7
  type: socks5
  server: 8.215.12.103
  port: 9050
- name: ID8
  type: socks5
  server: 8.215.15.163
  port: 104
- name: ID9
  type: socks5
  server: 8.215.3.250
  port: 19
- name: ID10
  type: socks5
  server: 149.129.255.179
  port: 3129
- name: TH1
  type: socks5
  server: 8.213.222.247
  port: 80
- name: TH2
  type: socks5
  server: 8.213.215.187
  port: 8889
- name: TH3
  type: socks5
  server: 8.213.215.187
  port: 104
- name: TH4
  type: socks5
  server: 8.213.215.187
  port: 80
- name: TH5
  type: socks5
  server: 8.213.222.157
  port: 80
- name: TH6
  type: socks5
  server: 8.213.222.157
  port: 3128
- name: TH7
  type: socks5
  server: 8.213.197.208
  port: 443
- name: TH8
  type: socks5
  server: 8.213.222.247
  port: 666
- name: TH9
  type: socks5
  server: 8.213.197.208
  port: 1081
- name: TH10
  type: socks5
  server: 8.213.197.208
  port: 8889
- name: SA1
  type: socks5
  server: 156.244.11.6
  port: 3129
- name: SA2
  type: socks5
  server: 156.244.11.6
  port: 2000
- name: SA3
  type: socks5
  server: 156.244.11.6
  port: 80
- name: MY1
  type: socks5
  server: 47.250.155.254
  port: 9098
- name: MY2
  type: socks5
  server: 47.250.155.254
  port: 8081
- name: MY3
  type: socks5
  server: 47.250.51.110
  port: 8080
- name: MY4
  type: socks5
  server: 47.250.177.202
  port: 8008
- name: MY5
  type: socks5
  server: 47.250.51.110
  port: 1081
- name: MY6
  type: socks5
  server: 47.250.177.202
  port: 6379
- name: MY7
  type: socks5
  server: 47.250.51.110
  port: 50070
- name: MY8
  type: socks5
  server: 47.250.177.202
  port: 3129
- name: MY9
  type: socks5
  server: 47.250.155.254
  port: 5060
- name: MY10
  type: socks5
  server: 47.250.11.111
  port: 102
- name: United Arab Emirates1
  type: socks5
  server: 47.91.110.148
  port: 9080
- name: United Arab Emirates2
  type: socks5
  server: 47.91.120.190
  port: 8443
- name: United Arab Emirates3
  type: socks5
  server: 47.91.110.148
  port: 13
- name: United Arab Emirates4
  type: socks5
  server: 47.91.120.190
  port: 10
- name: United Arab Emirates5
  type: socks5
  server: 38.54.9.151
  port: 8888
- name: 英国1
  type: socks5
  server: 8.211.200.183
  port: 8080
- name: 英国2
  type: socks5
  server: 8.211.194.78
  port: 1080
- name: 英国3
  type: socks5
  server: 8.211.200.183
  port: 2019
- name: 英国4
  type: socks5
  server: 8.211.200.183
  port: 84
- name: 英国5
  type: socks5
  server: 8.211.194.78
  port: 1081
- name: 英国6
  type: socks5
  server: 8.211.194.78
  port: 6379
- name: 英国7
  type: socks5
  server: 8.211.195.173
  port: 10000
- name: 英国8
  type: socks5
  server: 8.211.195.173
  port: 18080
- name: 英国9
  type: socks5
  server: 8.208.85.34
  port: 6969
- name: 英国10
  type: socks5
  server: 8.208.90.243
  port: 8081
- name: AE1
  type: socks5
  server: 47.91.121.127
  port: 11
- name: AE2
  type: socks5
  server: 47.91.107.139
  port: 8118
- name: AE3
  type: socks5
  server: 38.54.9.151
  port: 3129
- name: AE4
  type: socks5
  server: 47.91.109.17
  port: 8888
- name: AE5
  type: socks5
  server: 47.91.109.17
  port: 8118
- name: AE6
  type: socks5
  server: 47.91.109.17
  port: 6379
- name: AE7
  type: socks5
  server: 47.91.115.179
  port: 98
- name: AE8
  type: socks5
  server: 47.91.115.179
  port: 8090
- name: AE9
  type: socks5
  server: 47.91.121.127
  port: 3128
proxy-groups:
- name: 国家选择
  type: select
  proxies:
  - RU
  - 美国
  - 中国大陆
  - 韩国
  - 德国
  - PH
  - 香港
  - 日本
  - 新加坡
  - ID
  - TH
  - SA
  - MY
  - United Arab Emirates
  - 英国
  - AE
  - DIRECT
- name: RU
  type: url-test
  proxies:
  - RU1
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 美国
  type: url-test
  proxies:
  - 美国1
  - 美国2
  - 美国3
  - 美国4
  - 美国5
  - 美国6
  - 美国7
  - 美国8
  - 美国9
  - 美国10
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 中国大陆
  type: url-test
  proxies:
  - 中国大陆1
  - 中国大陆2
  - 中国大陆3
  - 中国大陆4
  - 中国大陆5
  - 中国大陆6
  - 中国大陆7
  - 中国大陆8
  - 中国大陆9
  - 中国大陆10
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 韩国
  type: url-test
  proxies:
  - 韩国1
  - 韩国2
  - 韩国3
  - 韩国4
  - 韩国5
  - 韩国6
  - 韩国7
  - 韩国8
  - 韩国9
  - 韩国10
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 德国
  type: url-test
  proxies:
  - 德国1
  - 德国2
  - 德国3
  - 德国4
  - 德国5
  - 德国6
  - 德国7
  - 德国8
  - 德国9
  - 德国10
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: PH
  type: url-test
  proxies:
  - PH1
  - PH2
  - PH3
  - PH4
  - PH5
  - PH6
  - PH7
  - PH8
  - PH9
  - PH10
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 香港
  type: url-test
  proxies:
  - 香港1
  - 香港2
  - 香港3
  - 香港4
  - 香港5
  - 香港6
  - 香港7
  - 香港8
  - 香港9
  - 香港10
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 日本
  type: url-test
  proxies:
  - 日本1
  - 日本2
  - 日本3
  - 日本4
  - 日本5
  - 日本6
  - 日本7
  - 日本8
  - 日本9
  - 日本10
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 新加坡
  type: url-test
  proxies:
  - 新加坡1
  - 新加坡2
  - 新加坡3
  - 新加坡4
  - 新加坡5
  - 新加坡6
  - 新加坡7
  - 新加坡8
  - 新加坡9
  - 新加坡10
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: ID
  type: url-test
  proxies:
  - ID1
  - ID2
  - ID3
  - ID4
  - ID5
  - ID6
  - ID7
  - ID8
  - ID9
  - ID10
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: TH
  type: url-test
  proxies:
  - TH1
  - TH2
  - TH3
  - TH4
  - TH5
  - TH6
  - TH7
  - TH8
  - TH9
  - TH10
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: SA
  type: url-test
  proxies:
  - SA1
  - SA2
  - SA3
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: MY
  type: url-test
  proxies:
  - MY1
  - MY2
  - MY3
  - MY4
  - MY5
  - MY6
  - MY7
  - MY8
  - MY9
  - MY10
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: United Arab Emirates
  type: url-test
  proxies:
  - United Arab Emirates1
  - United Arab Emirates2
  - United Arab Emirates3
  - United Arab Emirates4
  - United Arab Emirates5
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 英国
  type: url-test
  proxies:
  - 英国1
  - 英国2
  - 英国3
  - 英国4
  - 英国5
  - 英国6
  - 英国7
  - 英国8
  - 英国9
  - 英国10
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: AE
  type: url-test
  proxies:
  - AE1
  - AE2
  - AE3
  - AE4
  - AE5
  - AE6
  - AE7
  - AE8
  - AE9
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- DOMAIN-SUFFIX,local,DIRECT
- GEOIP,LAN,DIRECT
- GEOIP,CN,DIRECT
- MATCH,RU
